### ISSUE TITLE
Wrong documentation on crudkit.com

### ISSUE THREAD

**Issue by najiji** [skyronic/crudkit#21]
I managed to get crudkit to work, but there are, in my opinion, some serious documentation errors on *crudkit.com* in the section *How does it work*.

* Instead of `use CrudKit\MySQLTablePage;` `use CrudKit\Pages\MySQLTablePage;`
* Constructor of MySQLTablePage requires at least 4 arguments. `new MySQLTablePage ("page_id", "username", "password", "database");` instead of `new MySQLTablePage ("john", "hunter2", "mydb");`
* A mySQL page requires a summary collumn `->setSummaryColumns(array("column1", "column2"))`

I don't know wheter these things are bugs in the code and the demo should work, or the documentation is wrong indeed.

**Comment by skyronic** [comment]
Yes, you're right. Thank you for pointing this out. I'm fixing and updating the documentation.

**Comment by skyronic** [comment]
Now I remember why this error came up. I actually built the website first and wrote some preliminary docs before actually jumping into the code (because I'd procrastinate doing the docs and do code instead).

As a result, some initial "mockups" of how the code should look was stuck on the homepage. I've updated the homepage.
