### ISSUE TITLE
Upload docs to this repository?

### ISSUE THREAD

**Issue by wosevision** [skyronic/crudkit#90]
Hello!

I noticed recently that Crudkit is no longer maintained. Sad to see it retired, but I understand given it's a bit of an older project and I'm sure a lot has changed for you since.

That said, it looks like a lot of people (myself included!) are still using it, because it's still a very nice piece of software that fills the need for an extremely simple-to-configure database CRUD layer. There are others that can do this, but none so easy.

I was wondering – would it be possible to have the documentation that used to be featured at crudkit.com pushed to this repository for retrospective reading? It would be nice if people using it in their projects could still have those as a reference.

Thanks for bringing us Crudkit!

**Comment by skyronic** [comment]
Hello @wosevision !

Thank you so much for your note!

Unfortunately due to time constraints I could not keep things up to date. I really would like to give this more attention in the future. I've brought back the original site along with the docs [here](http://old.crudkit.com/docs/), and have also added a note to the website to find the docs.

Lemme know if you have any problems accessing the docs.

**Comment by wosevision** [comment]
That's wonderful, thanks @skyronic for taking the time to bring back the old docs! I really appreciate it, and again, really appreciate the fine work you've put into Crudkit.

If you ever revive the project, give me a shout if you find yourself in need an extra maintainer! I've had to do a lot of digging in Crudkit's internals for my organization's fork and have developed some familiarity with the codebase on account of that. I'd love the opportunity to give back to this labour of love you created.
